/**
 * v20 M7 — learning config "advancedDataStructures" English locale（AI initial translation, subject to user review in M7-7）
 *
 * ⚠️ This file is generated by AI translation. Source: src/i18n/locales/zh/learning/advancedDataStructures.ts
 * User review pass: M7-7.
 *
 * Structure:
 *   title/description/complexityTime/complexitySpace: string
 *   tips/highlightTerms: string (separated by |, consumed as .split('|'))
 */
export const advancedDataStructuresLearningSteps = {
  steps: {
    "redBlackTree": {
      title: 'Red-Black Tree Applications',
      description: 'A red-black tree is a self-balancing binary search tree. Color constraints guarantee that the longest path is at most twice the shortest, and search/insert/delete are all O(log n). Java TreeMap, C++ std::map, and the Linux CFS process scheduler are all built on red-black trees.',
      tips: 'Red-black trees require fewer rotations than AVL trees, making insert and delete more efficient, so they are preferred in production|AVL trees are more strictly balanced for lookups.',
      highlightTerms: 'red-black tree|O(log n)|rotation|recolor',
      complexityTime: 'O(log n)',
      complexitySpace: 'O(n)',
    },
    "bTree": {
      title: 'B-Tree Database Indexes',
      description: 'A B-tree is a multi-way balanced search tree where each node can hold multiple keys and children, optimized for disk storage. Database indexes (MySQL InnoDB) use B+ trees to reduce the number of disk I/Os.',
      tips: 'B-tree nodes are usually sized to match a disk page (e.g., 16KB), so a single I/O reads an entire node — the structure is literally "born for disk".',
      highlightTerms: 'B-tree|B+ tree|disk I/O|fanout',
      complexityTime: 'O(log n)',
      complexitySpace: 'O(n)',
    },
    "skipList": {
      title: 'Skip Lists in Redis',
      description: 'A skip list uses multi-level index linked lists to achieve O(log n) search — a probabilistic alternative to balanced trees. Redis sorted sets (ZSET) and LevelDB MemTables are both built on skip lists.',
      tips: 'Skip lists are far simpler to implement than red-black trees (no rotations) and support efficient range queries — the Redis author explicitly chose skip lists over balanced trees.',
      highlightTerms: 'skip list|multi-level|O(log n)|Redis',
      complexityTime: 'O(log n)',
      complexitySpace: 'O(n)',
    },
    "bloomFilter": {
      title: 'Bloom Filter',
      description: 'A Bloom filter is a probabilistic data structure that uses a bit array plus multiple hash functions to determine whether an element "possibly exists" or "definitely does not". It is extremely space efficient and is used for cache-penetration protection and spam filtering.',
      tips: 'A 1MB bit array with 7 hash functions can hold about 100K elements with a ~1% false-positive rate|It cannot delete elements (a counting Bloom filter can).',
      highlightTerms: 'Bloom filter|bit array|hash function|false positive rate',
      complexityTime: 'O(k)',
      complexitySpace: 'O(m)',
    },
    "unionFind": {
      title: 'Union-Find (DSU)',
      description: 'Union-Find (Disjoint Set Union) efficiently handles the merging and querying of disjoint sets. Combined with path compression and union by rank, a single operation is nearly O(1). It is used in Kruskal\'s MST, connected components, and network connectivity checks.',
      tips: 'With path compression and union by rank, the amortized cost per operation is O(α(n)) where α(n) < 5 for n < 10⁸⁰ — effectively O(1).',
      highlightTerms: 'union-find|path compression|union by rank|connected',
      complexityTime: 'O(α(n)) approximately O(1)',
      complexitySpace: 'O(n)',
    },
  },
} as const
