/**
 * v20 M7 — learning config "array" English locale（AI initial translation, subject to user review in M7-7）
 *
 * ⚠️ This file is generated by AI translation. Source: src/i18n/locales/zh/learning/array.ts
 * User review pass: M7-7.
 *
 * Structure:
 *   title/description/complexityTime/complexitySpace: string
 *   tips/highlightTerms: string (separated by |, consumed as .split('|'))
 */
export const arrayLearningSteps = {
  steps: {
    "structure": {
      title: 'Array Structure',
      description: 'Arrays are stored contiguously in memory; each element is accessed directly by its index, supporting O(1) random access.',
      tips: 'Contiguous memory layout gives arrays high cache hit rates, which is the fundamental reason array traversal is fast.',
      highlightTerms: 'index|contiguous',
      complexityTime: 'Random access O(1)',
      complexitySpace: 'O(n)',
    },
    "insert": {
      title: 'Insert Operation',
      description: 'Inserting an element at a given position requires shifting all subsequent elements one slot to the right, taking O(n) time.',
      tips: 'Tail insertion is O(1), but mid/head insertion is O(n) — this is the main drawback of arrays.',
      highlightTerms: 'arr[i - 1]|shift right',
    },
    "delete": {
      title: 'Delete Operation',
      description: 'Deleting an element at a given position requires shifting all subsequent elements one slot to the left, taking O(n) time.',
      tips: 'If order does not matter, you can use arr[i] = arr[arr.length-1] to delete in O(1).',
      highlightTerms: 'arr[i + 1]|shift left',
    },
    "search": {
      title: 'Search Operation',
      description: 'Linear search compares elements one by one, taking O(n); for sorted arrays, binary search gives O(log n).',
      tips: 'Arrays are the most fundamental data structure — almost every other structure is built on top of them.',
      highlightTerms: 'arr[i] === target|O(n)',
    },
    "searchAll": {
      title: 'Find All',
      description: 'Linear search that collects the indices of all matching elements, taking O(n). Useful when duplicates may exist.',
      tips: 'Finding all matches is still O(n); sortedness cannot speed it up because every element must be checked.',
      highlightTerms: 'indices.push(i)|O(n)',
    },
    "binarySearch": {
      title: 'Binary Search',
      description: 'Requires the array to be sorted in ascending order. Compare the middle element each time and halve the search range, taking O(log n) time.',
      tips: 'Binary search requires a sorted array; otherwise the result is unreliable|Each iteration halves the range: n → n/2 → n/4 → ... → 1, totaling log₂(n) steps|mid = (lo + hi) >> 1 is equivalent to Math.floor((lo + hi) / 2); bitwise is slightly faster',
      highlightTerms: 'mid = (lo + hi) >> 1|O(log n)',
      complexityTime: 'O(log n)',
      complexitySpace: 'O(1)',
    },
  },
} as const
