/**
 * v20 M7 — learning config "avlTree" English locale（AI initial translation, subject to user review in M7-7）
 *
 * ⚠️ This file is generated by AI translation. Source: src/i18n/locales/zh/learning/avlTree.ts
 * User review pass: M7-7.
 *
 * Structure:
 *   title/description/complexityTime/complexitySpace: string
 *   tips/highlightTerms: string (separated by |, consumed as .split('|'))
 */
export const avlTreeLearningSteps = {
  steps: {
    "concept": {
      title: 'AVL Tree Concept',
      description: 'A self-balancing binary search tree where the absolute balance factor of any node is at most 1.',
      tips: 'AVL trees were invented by Adelson-Velsky and Landis in 1962|Rotations keep the tree balanced, ensuring search/insert/delete stay O(log n)',
      highlightTerms: 'height',
      complexityTime: 'O(log n)',
      complexitySpace: 'O(n)',
    },
    "height-balance": {
      title: 'Height and Balance Factor',
      description: 'Node height = max(left subtree height, right subtree height) + 1; balance factor = left height - right height.',
      tips: 'Leaf node height is 1; null node height is 0|Balance factor must be in {-1, 0, 1}; otherwise a rotation is needed',
      highlightTerms: 'getHeight|getBalanceFactor',
    },
    "insert": {
      title: 'Insert Node',
      description: 'Insert as in a regular BST, then walk up the path updating heights and checking balance.',
      tips: 'After insertion you must walk from the inserted node back to the root|Update heights and check the balance factor along the way',
      highlightTerms: 'height|rebalance',
    },
    "rotations": {
      title: 'Rotation Operations',
      description: 'Four imbalance cases: LL (right rotation), RR (left rotation), LR (left then right), RL (right then left).',
      tips: 'LL: balance factor > 1 and the new node is in the left child\'s left subtree|LR: left-rotate the left subtree, then right-rotate the root|RR and RL are symmetric cases',
      highlightTerms: 'rotateRight|x.right = y',
    },
    "rebalance": {
      title: 'Rebalance',
      description: 'Determine the imbalance type from the balance factor and apply the corresponding rotation.',
      tips: 'Check the child node\'s balance factor to identify the imbalance type|LR and RL cases need two rotations to recover',
      highlightTerms: 'bf > 1|bf < -1|rotateRight|rotateLeft',
    },
    "delete": {
      title: 'Delete Node',
      description: 'Delete as in a BST, replace a node with two children by its inorder successor, then rebalance.',
      tips: 'After deletion, multiple rotations may be needed to recover balance|The inorder successor is the smallest node in the right subtree',
      highlightTerms: 'successor|findMin|rebalance',
      complexityTime: 'O(log n)',
      complexitySpace: 'O(log n)',
    },
    "complexity": {
      title: 'Complexity Analysis',
      description: 'AVL trees guarantee height O(log n) and all operations run in O(log n).',
      tips: 'AVL trees are more strictly balanced than red-black trees: faster lookups but more rotations on insert/delete|Suited to lookup-heavy scenarios like database index caches',
      highlightTerms: 'log2|O(log n)',
    },
  },
} as const
