/**
 * v20 M7 — learning config "bellmanFord" English locale（AI initial translation, subject to user review in M7-7）
 *
 * ⚠️ This file is generated by AI translation. Source: src/i18n/locales/zh/learning/bellmanFord.ts
 * User review pass: M7-7.
 *
 * Structure:
 *   title/description/complexityTime/complexitySpace: string
 *   tips/highlightTerms: string (separated by |, consumed as .split('|'))
 */
export const bellmanFordLearningSteps = {
  steps: {
    "init": {
      title: 'Initialize Distance Table',
      description: 'Set the distance of all nodes to infinity and the source node to 0. Unlike Dijkstra, Bellman-Ford can handle negative-weight edges.',
      tips: 'Infinity means no path has been found yet; the source starts at 0.',
      highlightTerms: 'dist[start] = 0|Infinity',
      complexityTime: 'O(V·E)',
      complexitySpace: 'O(V)',
    },
    "relax": {
      title: 'Edge Relaxation (V-1 Rounds)',
      description: 'Run V-1 rounds of relaxation on all edges. Each round iterates over every edge and tries to update a neighbor\'s shortest distance via the current distances.',
      tips: 'V-1 rounds is enough because a shortest path uses at most V-1 edges|If a round makes no updates, the algorithm can stop early.',
      highlightTerms: 'dist[u] + w|dist[v]',
    },
    "negative-cycle": {
      title: 'Negative-Cycle Detection',
      description: 'If the V-th round can still relax an edge, a negative-weight cycle exists — distances can be reduced indefinitely.',
      tips: 'A negative-weight cycle means distances can be reduced without bound, so shortest paths are undefined|Dijkstra cannot detect negative-weight cycles.',
      highlightTerms: 'dist[u] + w < dist[v]|negative cycle',
      complexityTime: 'O(V·E)',
      complexitySpace: 'O(V)',
    },
    "complete": {
      title: 'Algorithm Complete',
      description: 'The dist table holds the shortest distance from the source to every node (if no negative cycle exists).',
      tips: 'Bellman-Ford trades speed for the ability to handle negative-weight edges.',
      highlightTerms: 'dist|negative weight',
    },
  },
} as const
