/**
 * v20 M7 — learning config "bfs" English locale（AI initial translation, subject to user review in M7-7）
 *
 * ⚠️ This file is generated by AI translation. Source: src/i18n/locales/zh/learning/bfs.ts
 * User review pass: M7-7.
 *
 * Structure:
 *   title/description/complexityTime/complexitySpace: string
 *   tips/highlightTerms: string (separated by |, consumed as .split('|'))
 */
export const bfsLearningSteps = {
  steps: {
    "init": {
      title: 'Initialization',
      description: 'Create a queue and enqueue the starting node.',
      tips: 'BFS uses a queue (FIFO), while DFS uses a stack (LIFO) — this is the essential difference between the two.',
      highlightTerms: 'queue|start',
      complexityTime: 'O(V+E)',
      complexitySpace: 'O(V)',
    },
    "dequeue": {
      title: 'Dequeue',
      description: 'Remove a node from the head of the queue.',
      tips: 'BFS naturally traverses level by level; the first time a node is reached gives the shortest path (in unweighted graphs).',
      highlightTerms: 'shift',
    },
    "visit": {
      title: 'Visit Node',
      description: 'Mark the current node as visited.',
      tips: 'Mark a node as visited when it is enqueued (not dequeued) to avoid enqueuing duplicates.',
      highlightTerms: 'visited|add',
    },
    "neighbors": {
      title: 'Traverse Neighbors',
      description: 'Enqueue all unvisited neighbor nodes.',
      tips: 'Common BFS use cases: shortest path (unweighted), level-order traversal, finding first/second-degree friends in social networks.',
      highlightTerms: 'push|queue',
    },
  },
} as const
