/**
 * v20 M7 — learning config "bTree" English locale（AI initial translation, subject to user review in M7-7）
 *
 * ⚠️ This file is generated by AI translation. Source: src/i18n/locales/zh/learning/bTree.ts
 * User review pass: M7-7.
 *
 * Structure:
 *   title/description/complexityTime/complexitySpace: string
 *   tips/highlightTerms: string (separated by |, consumed as .split('|'))
 */
export const bTreeLearningSteps = {
  steps: {
    "concept": {
      title: 'B-Tree Concept',
      description: 'A multi-way self-balancing search tree where each node stores multiple keys and all leaves are at the same level.',
      tips: 'B-trees were proposed by Bayer and McCreight in 1972|Each node has at most order children and order-1 keys|All leaves are at the same level, guaranteeing balance',
      highlightTerms: 'keys|children|leaf',
      complexityTime: 'O(log n)',
      complexitySpace: 'O(n)',
    },
    "node-structure": {
      title: 'Node Structure',
      description: 'In a B-tree of order m: each node has at most m-1 keys and m children; non-root nodes have at least ⌈m/2⌉-1 keys.',
      tips: 'The order m determines the maximum number of children per node|A 2-3 tree is the simplest B-tree (m=3)|B+ tree is a B-tree variant, commonly used for database indexes',
      highlightTerms: 'order|2-3 tree',
    },
    "insert": {
      title: 'Insert Operation',
      description: 'Starting from the root, find a suitable leaf and insert the key. If the node is already full, a split is triggered.',
      tips: 'Insertion always happens at a leaf|Always check whether the node is full before inserting|A full node must be split before insertion can continue',
      highlightTerms: 'insertNonFull|splitChild',
    },
    "split": {
      title: 'Split Mechanism',
      description: 'When a node exceeds maxKeys, the middle key is pushed up to the parent and the node splits into two halves.',
      tips: 'Splitting is the core operation that keeps a B-tree balanced|The middle key is promoted to the parent|Splitting may propagate all the way up to the root',
      highlightTerms: 'midKey|slice|splice',
    },
    "search": {
      title: 'Search Operation',
      description: 'Start from the root, find the right slot in keys, and recurse/iterate into the corresponding child.',
      tips: 'Search time complexity is O(log n)|Each node\'s keys are sorted, so binary search can be used within a node|The search path goes from root to leaf, with length equal to tree height',
      highlightTerms: 'key === node.keys[i]|node.children[i]',
    },
    "balance": {
      title: 'Balance Property',
      description: 'B-trees guarantee all leaves are at the same level via the split mechanism, so the height is always O(log n).',
      tips: 'B-tree balance is natural — splitting keeps leaves on the same level|Unlike AVL/red-black, B-trees do not need rotations|A larger order means a shorter tree, ideal for disk I/O',
      highlightTerms: 'same level|log',
    },
    "applications": {
      title: 'Applications',
      description: 'B-trees are widely used in database indexes and file systems; the multi-way property reduces disk I/O.',
      tips: 'B+ tree is the top choice for database indexes|Node size usually matches disk block size (4KB-16KB)|B-tree vs B+ tree: B+ trees link leaves in a list, making range queries more efficient',
      highlightTerms: 'B+ tree|disk I/O',
      complexityTime: 'O(log n)',
      complexitySpace: 'O(n)',
    },
  },
} as const
