/**
 * v20 M7 — learning config "bubble" English locale（AI initial translation, subject to user review in M7-7）
 *
 * ⚠️ This file is generated by AI translation. Source: src/i18n/locales/zh/learning/bubble.ts
 * User review pass: M7-7.
 *
 * Structure:
 *   title/description/complexityTime/complexitySpace: string
 *   tips/highlightTerms: string (separated by |, consumed as .split('|'))
 */
export const bubbleLearningSteps = {
  steps: {
    "init": {
      title: 'Initialization',
      description: 'The outer loop iterates the array from left to right; each pass "bubbles" the maximum value to the end.',
      tips: 'Bubble sort is the most intuitive sorting algorithm but has low efficiency, making it suitable for teaching rather than production.',
      highlightTerms: 'n - 1',
      complexityTime: 'O(n²)',
      complexitySpace: 'O(1)',
    },
    "compare": {
      title: 'Compare Adjacent Elements',
      description: 'Compare arr[j] and arr[j+1] to decide whether a swap is needed.',
      tips: 'Each pass shrinks the comparison range by i elements, because the last i elements are already in place.',
      highlightTerms: 'arr[j]|arr[j + 1]',
    },
    "swap": {
      title: 'Swap Elements',
      description: 'If the left element is greater than the right, swap the two elements.',
      tips: 'Bubble sort is stable — equal elements never swap positions.',
      highlightTerms: 'temp|arr[j]',
    },
    "sorted": {
      title: 'Sorted Region',
      description: 'After each pass, the maximum element reaches its correct position, and the comparison range shrinks.',
      tips: 'Adding a swapped flag allows early termination when no swap occurs in a pass, giving a best case of O(n).',
      highlightTerms: 'sorted region|O(n)',
    },
  },
} as const
