/**
 * v20 M7 — learning config "bucket" English locale（AI initial translation, subject to user review in M7-7）
 *
 * ⚠️ This file is generated by AI translation. Source: src/i18n/locales/zh/learning/bucket.ts
 * User review pass: M7-7.
 *
 * Structure:
 *   title/description/complexityTime/complexitySpace: string
 *   tips/highlightTerms: string (separated by |, consumed as .split('|'))
 */
export const bucketLearningSteps = {
  steps: {
    "init": {
      title: 'Create Buckets',
      description: 'Determine the number of buckets and their range, then create the empty bucket array.',
      tips: 'The number of buckets is usually taken as √n, which is an empirical balance point.',
      highlightTerms: 'bucketCount|bucketRange',
      complexityTime: 'O(n+k)',
      complexitySpace: 'O(n+k)',
    },
    "distribute": {
      title: 'Distribute Elements',
      description: 'Iterate the array and place each element into its corresponding bucket.',
      tips: 'Math.min ensures that the maximum value does not overflow into a non-existent bucket.',
      highlightTerms: 'bucketIdx|push',
    },
    "sort": {
      title: 'Sort Within Buckets',
      description: 'Sort each bucket individually (typically with insertion sort or a built-in sort).',
      tips: 'The choice of intra-bucket sort depends on the data distribution; insertion sort is more efficient when buckets are small.',
      highlightTerms: 'sort',
    },
    "merge": {
      title: 'Merge Results',
      description: 'Walk the buckets in order and concatenate their elements back into the original array.',
      tips: 'Bucket sort approaches O(n) on uniformly distributed data, but degrades to O(n²) when the distribution is highly skewed.',
      highlightTerms: 'arr[idx]|buckets[b]',
      complexityTime: 'Average O(n+k), worst O(n²)',
      complexitySpace: 'O(n+k)',
    },
  },
} as const
