/**
 * v20 M7 — learning config "comb" English locale（AI initial translation, subject to user review in M7-7）
 *
 * ⚠️ This file is generated by AI translation. Source: src/i18n/locales/zh/learning/comb.ts
 * User review pass: M7-7.
 *
 * Structure:
 *   title/description/complexityTime/complexitySpace: string
 *   tips/highlightTerms: string (separated by |, consumed as .split('|'))
 */
export const combLearningSteps = {
  steps: {
    "gap": {
      title: 'Shrink Gap',
      description: 'Comb sort uses a shrink factor of 1.3 to progressively reduce the comparison gap, eliminating the "turtle" problem of bubble sort.',
      tips: '1.3 is the empirically optimal shrink factor|Turtle problem: small values at the end of the array move very slowly.',
      highlightTerms: 'shrink = 1.3|gap',
      complexityTime: 'O(n log n)',
      complexitySpace: 'O(1)',
    },
    "compare-swap": {
      title: 'Gap Compare and Swap',
      description: 'Compare elements spaced gap apart; if they are out of order, swap them.',
      tips: 'Large gaps let elements move across long distances quickly|The swapped flag ensures the array is fully sorted when gap=1.',
      highlightTerms: 'arr[i] > arr[i + gap]|swapped = true',
    },
    "complete": {
      title: 'Algorithm Complete',
      description: 'Sorting completes when gap=1 and no swap occurs.',
      tips: 'Comb sort is an improvement on bubble sort|Average performance is better than bubble, approaching O(n log n).',
      highlightTerms: 'gap=1|nearly sorted',
      complexityTime: 'O(n log n)',
      complexitySpace: 'O(1)',
    },
  },
} as const
