/**
 * v20 M7 — learning config "complexityAnalysis" English locale（AI initial translation, subject to user review in M7-7）
 *
 * ⚠️ This file is generated by AI translation. Source: src/i18n/locales/zh/learning/complexityAnalysis.ts
 * User review pass: M7-7.
 *
 * Structure:
 *   title/description/complexityTime/complexitySpace: string
 *   tips/highlightTerms: string (separated by |, consumed as .split('|'))
 */
export const complexityAnalysisLearningSteps = {
  steps: {
    "concept": {
      title: 'Time Complexity Concept',
      description: 'Time complexity measures how an algorithm\'s running time grows with the input size, not the actual execution time, making it easy to compare algorithm efficiency across the board.',
      tips: 'Time complexity describes a "growth trend", not a "real runtime" — an O(n) algorithm on small n can be slower than O(log n) because of the constant factor.',
      highlightTerms: 'O(n)|trend|input size',
      complexityTime: 'analysis framework',
      complexitySpace: 'O(1)',
    },
    "bigO": {
      title: 'Big-O Notation',
      description: 'Big-O notation describes an upper bound on an algorithm. Common complexities from best to worst: O(1) < O(log n) < O(n) < O(n log n) < O(n²) < O(2ⁿ) < O(n!).',
      tips: 'O(log n) means each step halves the problem — 2³² elements only need 32 operations to locate.',
      highlightTerms: 'O(1)|O(log n)|O(n)|O(n²)',
    },
    "space": {
      title: 'Space Complexity',
      description: 'Space complexity measures how the extra memory an algorithm uses during execution grows with the input size, including auxiliary variables, the recursion stack, and dynamically allocated structures.',
      tips: 'The space complexity of a recursive algorithm must include the call stack: a recursion of depth d uses O(d) space.',
      highlightTerms: 'O(1)|O(n)|O(log n)|recursion stack',
    },
    "cases": {
      title: 'Best / Worst / Average Cases',
      description: 'The same algorithm behaves differently on different inputs. Quicksort is worst O(n²) (on sorted input) and average O(n log n); searching is best O(1) (first element hit) and worst O(n).',
      tips: 'In engineering we care most about the average case, because worst cases usually require specially crafted input|Real-time systems, however, must consider the worst case.',
      highlightTerms: 'best case|worst case|average case',
    },
    "amortized": {
      title: 'Amortized Analysis',
      description: 'Amortized analysis evaluates the total cost of a sequence of operations divided by the number of operations. A single dynamic array resize is O(n), but n inserts amortize to O(1) because resizes become rarer as the array grows.',
      tips: 'Three methods of amortized analysis: aggregate (sum-and-average), accounting (pre-deposit), and potential (potential function).',
      highlightTerms: 'amortized|O(1)|resize',
      complexityTime: 'Amortized O(1)',
      complexitySpace: 'O(n)',
    },
  },
} as const
