/**
 * v20 M7 — learning config "counting" English locale（AI initial translation, subject to user review in M7-7）
 *
 * ⚠️ This file is generated by AI translation. Source: src/i18n/locales/zh/learning/counting.ts
 * User review pass: M7-7.
 *
 * Structure:
 *   title/description/complexityTime/complexitySpace: string
 *   tips/highlightTerms: string (separated by |, consumed as .split('|'))
 */
export const countingLearningSteps = {
  steps: {
    "init": {
      title: 'Determine Value Range',
      description: 'Find the maximum and minimum values in the array and determine the count array range k = max - min + 1.',
      tips: 'Counting sort is a non-comparison sort with O(n+k) time complexity, where k is the value range|It is very efficient when k << n, but the space cost grows when k is large.',
      highlightTerms: 'range|max|min',
      complexityTime: 'O(n+k)',
      complexitySpace: 'O(n+k)',
    },
    "count": {
      title: 'Count Occurrences',
      description: 'Iterate the array, count occurrences of each value, and store the counts in the count array.',
      tips: 'Using arr[i] - min as the index handles negative numbers|This step runs in O(n).',
      highlightTerms: 'count[arr[i] - min]|count',
    },
    "prefix": {
      title: 'Prefix Sum',
      description: 'Compute the prefix sum of the count array, converting the occurrence counts into the final position of each element in the output array.',
      tips: 'After the prefix sum, count[j] is the last (1-based) position of value (j+min) in the sorted output.',
      highlightTerms: 'count[i] += count[i - 1]',
    },
    "place": {
      title: 'Reverse Placement (Stable)',
      description: 'Iterate the original array in reverse and place each element at its correct position according to the count array.',
      tips: 'Reverse iteration is the key to stability — equal elements keep their relative order|After each placement count[idx] is decremented to point to the next slot for the same value.',
      highlightTerms: 'output[count[idx] - 1]|count[idx]--',
    },
    "copy": {
      title: 'Copy Back',
      description: 'Copy the sorted output array back into the original array to complete the sort.',
      tips: 'Counting sort is stable and works well for non-negative integers with a small value range|Time O(n+k), space O(n+k).',
      highlightTerms: 'arr[i] = output[i]',
    },
  },
} as const
