/**
 * v20 M7 — learning config "dfs" English locale（AI initial translation, subject to user review in M7-7）
 *
 * ⚠️ This file is generated by AI translation. Source: src/i18n/locales/zh/learning/dfs.ts
 * User review pass: M7-7.
 *
 * Structure:
 *   title/description/complexityTime/complexitySpace: string
 *   tips/highlightTerms: string (separated by |, consumed as .split('|'))
 */
export const dfsLearningSteps = {
  steps: {
    "init": {
      title: 'Initialization',
      description: 'Create a stack and push the starting node onto it.',
      tips: 'DFS can also be implemented with recursion — the call stack is itself a stack structure.',
      highlightTerms: 'stack|start',
      complexityTime: 'O(V+E)',
      complexitySpace: 'O(V)',
    },
    "pop": {
      title: 'Pop',
      description: 'Remove a node from the top of the stack.',
      tips: 'After popping, check whether the node is already visited because the same node may have been pushed onto the stack multiple times.',
      highlightTerms: 'pop',
    },
    "visit": {
      title: 'Visit Node',
      description: 'Mark the current node as visited and add it to the result.',
      tips: 'DFS goes depth-first, walking a path all the way to the end before backtracking. Great for cycle detection and topological sort.',
      highlightTerms: 'visited|add',
    },
    "neighbors": {
      title: 'Traverse Neighbors',
      description: 'Push all unvisited neighbor nodes onto the stack.',
      tips: 'Common DFS use cases: connected component detection, cycle detection, path search, maze solving, topological sort.',
      highlightTerms: 'push|stack',
    },
  },
} as const
