/**
 * v20 M7 — learning config "dijkstra" English locale（AI initial translation, subject to user review in M7-7）
 *
 * ⚠️ This file is generated by AI translation. Source: src/i18n/locales/zh/learning/dijkstra.ts
 * User review pass: M7-7.
 *
 * Structure:
 *   title/description/complexityTime/complexitySpace: string
 *   tips/highlightTerms: string (separated by |, consumed as .split('|'))
 */
export const dijkstraLearningSteps = {
  steps: {
    "init": {
      title: 'Initialization',
      description: 'Create a distance table with the source at distance 0 and the rest at infinity. Maintain a predecessor table to reconstruct the path.',
      tips: 'Initializing distances to Infinity simplifies later comparisons; the source starts at 0.',
      highlightTerms: 'distances[start] = 0|Infinity',
      complexityTime: 'O((V+E)log V)',
      complexitySpace: 'O(V)',
    },
    "select": {
      title: 'Select Closest Node',
      description: 'Pick the unvisited node with the smallest distance and mark it as visited.',
      tips: 'Using a priority queue (min-heap) reduces the selection step from O(V) to O(log V).',
      highlightTerms: 'distances[n]|minDist|visited',
    },
    "relax": {
      title: 'Relax Operation',
      description: 'Iterate all neighbors of the current node, compute the distance through the current node, and update if it is shorter.',
      tips: '"Relaxation" is the core idea in graph algorithms: try to find a shorter path to update the distance.',
      highlightTerms: 'newDist|distances[neighbor]',
    },
    "path": {
      title: 'Reconstruct Path',
      description: 'After the algorithm finishes, walk the predecessor table backward from the destination to the source to obtain the shortest path.',
      tips: 'Path reconstruction goes from destination back to source; use unshift to build the path in the natural order.',
      highlightTerms: 'previous[current]|path',
    },
    "complete": {
      title: 'Algorithm Complete',
      description: 'All nodes are processed; the distances table contains the shortest distance from the source to every node.',
      tips: 'Dijkstra cannot handle negative-weight edges; for negative-weight graphs use Bellman-Ford.',
      highlightTerms: 'distances|previous',
      complexityTime: 'O((V+E)log V) with heap optimization',
      complexitySpace: 'O(V+E)',
    },
  },
} as const
