/**
 * v20 M7 — learning config "doublyLinkedList" English locale（AI initial translation, subject to user review in M7-7）
 *
 * ⚠️ This file is generated by AI translation. Source: src/i18n/locales/zh/learning/doublyLinkedList.ts
 * User review pass: M7-7.
 *
 * Structure:
 *   title/description/complexityTime/complexitySpace: string
 *   tips/highlightTerms: string (separated by |, consumed as .split('|'))
 */
export const doublyLinkedListLearningSteps = {
  steps: {
    "structure": {
      title: 'Doubly Linked List Structure',
      description: 'Each node contains data, a prev pointer to the predecessor, and a next pointer to the successor.',
      tips: 'Doubly linked lists use one extra pointer compared to singly linked, but support reverse traversal and O(1) deletion of a known node.',
      highlightTerms: 'prev|next',
      complexityTime: 'Access O(n), insert/delete O(1)',
      complexitySpace: 'O(n)',
    },
    "insert-head": {
      title: 'Insert at Head',
      description: 'Set the new node\'s next to the original head, set the original head\'s prev to the new node, then update the head pointer.',
      tips: 'Head insertion needs to handle the special case where the list is empty (head is null).',
      highlightTerms: 'this.head.prev|node',
    },
    "insert-tail": {
      title: 'Insert at Tail',
      description: 'Traverse to the end of the list, link the new node at the tail, and establish the bidirectional pointers.',
      tips: 'Maintaining a tail pointer can optimize tail insertion to O(1); doubly linked lists make this easier to maintain.',
      highlightTerms: 'node.prev|curr',
    },
    "delete": {
      title: 'Delete Node',
      description: 'Find the target node; set its predecessor\'s next to its successor, and the successor\'s prev to its predecessor.',
      tips: 'Doubly linked list deletion does not need to find the predecessor because each node has its own prev pointer.',
      highlightTerms: 'curr.prev.next|curr.next.prev',
    },
    "insert-at": {
      title: 'Insert at Position',
      description: 'Traverse to the target position and establish the new node\'s bidirectional pointers with predecessor and successor.',
      tips: 'Doubly linked list insertion needs to maintain 4 pointers (2 directions × 2 nodes), 2 more than a singly linked list.',
      highlightTerms: 'node.prev|curr.next.prev',
    },
    "search": {
      title: 'Search',
      description: 'Traverse from the head, comparing each node value. Doubly linked lists can also search backwards from the tail.',
      tips: 'Doubly linked list search has the same O(n) complexity as singly linked, but supports bidirectional traversal.',
      highlightTerms: 'curr.value === value|while',
    },
    "reverse": {
      title: 'Reverse',
      description: 'Swap the prev and next pointers of each node, then update the head pointer.',
      tips: 'Reversing a doubly linked list is simpler than a singly linked list: just swap each node\'s prev/next|Note traversal direction: after swapping, curr.next becomes the original prev, so advance via curr.prev',
      highlightTerms: 'curr.prev|curr.next',
      complexityTime: 'O(n)',
      complexitySpace: 'O(1)',
    },
    "detect-cycle": {
      title: 'Cycle Detection',
      description: 'Floyd\'s tortoise-and-hare algorithm also applies to doubly linked lists; the slow and fast pointers meeting indicates a cycle.',
      tips: 'The cycle detection algorithm is identical to singly linked lists, because the cycle only involves the next pointer.',
      highlightTerms: 'slow === fast|fast.next.next',
      complexityTime: 'O(n)',
      complexitySpace: 'O(1)',
    },
  },
} as const
