/**
 * v20 M7 — learning config "floydWarshall" English locale（AI initial translation, subject to user review in M7-7）
 *
 * ⚠️ This file is generated by AI translation. Source: src/i18n/locales/zh/learning/floydWarshall.ts
 * User review pass: M7-7.
 *
 * Structure:
 *   title/description/complexityTime/complexitySpace: string
 *   tips/highlightTerms: string (separated by |, consumed as .split('|'))
 */
export const floydWarshallLearningSteps = {
  steps: {
    "init": {
      title: 'Initialize Distance Matrix',
      description: 'Build a V×V distance matrix: the diagonal is 0, direct edges carry their weight, and the remaining cells are infinity.',
      tips: 'Floyd-Warshall computes shortest paths between every pair of nodes|Uses an adjacency matrix to represent the graph.',
      highlightTerms: 'dist[i][i] = 0|Infinity',
      complexityTime: 'O(V³)',
      complexitySpace: 'O(V²)',
    },
    "relax": {
      title: 'Triple-Loop Relaxation',
      description: 'Use each node k as an intermediate, and try to relax the distance of every pair (i, j) through k.',
      tips: 'Core recurrence: dist[i][j] = min(dist[i][j], dist[i][k] + dist[k][j])|k must be the outermost loop.',
      highlightTerms: 'dist[i][k] + dist[k][j]|dist[i][j]',
    },
    "complete": {
      title: 'Algorithm Complete',
      description: 'The dist matrix holds the shortest distance between every pair of nodes.',
      tips: 'Floyd-Warshall is elegant but expensive; it suits dense graphs with few nodes|It can also detect negative cycles: if dist[i][i] < 0 there is a negative cycle.',
      highlightTerms: 'dist[i][j]',
      complexityTime: 'O(V³)',
      complexitySpace: 'O(V²)',
    },
  },
} as const
