/**
 * v20 M7 — learning config "graph" English locale（AI initial translation, subject to user review in M7-7）
 *
 * ⚠️ This file is generated by AI translation. Source: src/i18n/locales/zh/learning/graph.ts
 * User review pass: M7-7.
 *
 * Structure:
 *   title/description/complexityTime/complexitySpace: string
 *   tips/highlightTerms: string (separated by |, consumed as .split('|'))
 */
export const graphLearningSteps = {
  steps: {
    "structure": {
      title: 'Graph Structure',
      description: 'A graph consists of vertices (nodes) and edges. Edges can be directed and weighted. Adjacency matrices or adjacency lists are commonly used for storage.',
      tips: 'Sparse graphs use adjacency lists O(V+E), dense graphs use adjacency matrices O(V²); choose by edge density.',
      highlightTerms: 'vertex|edge|adjacency list',
      complexityTime: 'Depends on the operation',
      complexitySpace: 'Adjacency list O(V+E), adjacency matrix O(V²)',
    },
    "add-node": {
      title: 'Add Vertex',
      description: 'Add a new vertex to the graph, with its adjacency initialized to empty.',
      tips: 'After adding a vertex, you still need to add edges to establish relationships between nodes.',
      highlightTerms: 'adjacency|push',
    },
    "add-edge": {
      title: 'Add Edge',
      description: 'Create a connection between two vertices, optionally with a weight. Undirected graphs must add both directions.',
      tips: 'A directed graph only needs one edge; an undirected graph must add two opposite edges.',
      highlightTerms: 'adjacency[from]|weight',
    },
    "delete-node": {
      title: 'Delete Node',
      description: 'Delete a vertex and all its associated edges. All edges pointing to that vertex must be cleaned up in the adjacency list.',
      tips: 'Deleting a vertex must also clean up all associated edges|Deleting a vertex in an undirected graph requires cleaning up the adjacency list in both directions.',
      highlightTerms: 'filter|deleteNode|adjacency',
      complexityTime: 'O(V + E)',
      complexitySpace: 'O(1)',
    },
    "delete-edge": {
      title: 'Delete Edge',
      description: 'Delete the edge between two specified vertices. For undirected graphs, both directions must be removed from the adjacency list.',
      tips: 'A directed graph only needs to remove one direction; undirected must remove both|Deleting a non-existent edge should either silently ignore or return false.',
      highlightTerms: 'filter|deleteEdge',
      complexityTime: 'O(E), E is the number of edges of the vertex',
      complexitySpace: 'O(1)',
    },
    "bfs": {
      title: 'Breadth-First Search (BFS)',
      description: 'Use a queue to expand layer by layer, starting from the source and visiting all reachable vertices level by level. Best for shortest paths in unweighted graphs.',
      tips: 'BFS gives the shortest path in unweighted graphs|Uses a queue (FIFO) to preserve level order|Time complexity O(V + E).',
      highlightTerms: 'queue|shift|visited',
      complexityTime: 'O(V + E)',
      complexitySpace: 'O(V)',
    },
    "dfs": {
      title: 'Depth-First Search (DFS)',
      description: 'Use a stack or recursion to go as deep as possible along a path, then backtrack. Great for connectivity checks, topological sort, and cycle detection.',
      tips: 'DFS can detect cycles, perform topological sort, and find connected components|Recursive implementation is concise but risks stack overflow; use an explicit stack for large data|Time complexity O(V + E).',
      highlightTerms: 'dfs|visited|recursion',
      complexityTime: 'O(V + E)',
      complexitySpace: 'O(V) recursion stack',
    },
    "dijkstra": {
      title: 'Dijkstra Shortest Path',
      description: 'Use a priority queue for greedy expansion to find single-source shortest paths. Solves shortest paths in weighted graphs (with non-negative weights).',
      tips: 'Dijkstra cannot handle negative-weight edges (use Bellman-Ford)|With a priority queue the complexity is O((V+E) log V)|In practice, a binary heap should be used rather than array sorting.',
      highlightTerms: 'dist|pq|weight',
      complexityTime: 'O((V+E) log V)',
      complexitySpace: 'O(V)',
    },
  },
} as const
