/**
 * v20 M7 — learning config "hash" English locale（AI initial translation, subject to user review in M7-7）
 *
 * ⚠️ This file is generated by AI translation. Source: src/i18n/locales/zh/learning/hash.ts
 * User review pass: M7-7.
 *
 * Structure:
 *   title/description/complexityTime/complexitySpace: string
 *   tips/highlightTerms: string (separated by |, consumed as .split('|'))
 */
export const hashLearningSteps = {
  steps: {
    "init": {
      title: 'Hash Function',
      description: 'Map keys to array indices through a hash function, achieving O(1) average access.',
      tips: 'A good hash function distributes keys uniformly to reduce collisions. Common examples include multiplicative hash and MurmurHash.',
      highlightTerms: 'hash % size',
      complexityTime: 'Average O(1), worst O(n)',
      complexitySpace: 'O(n)',
    },
    "insert": {
      title: 'Insert Key-Value Pair',
      description: 'Compute the hash value to determine the bucket, and store the key-value pair in that bucket.',
      tips: 'When the load factor (number of elements / number of buckets) exceeds 0.75, the table usually needs to be resized and rehashed.',
      highlightTerms: 'hash(key)|push',
    },
    "collision": {
      title: 'Collision Handling',
      description: 'When multiple keys map to the same index, use separate chaining to store multiple elements in the bucket.',
      tips: 'The two main collision strategies: separate chaining (used here) and open addressing.',
      highlightTerms: 'find|item.key',
    },
    "search": {
      title: 'Search Operation',
      description: 'Compute the hash value to locate the bucket, then walk the chain inside the bucket to find the matching key.',
      tips: 'A hash table is the underlying implementation of JavaScript objects and Map, and is one of the most important data structures.',
      highlightTerms: 'item.key === key',
    },
    "remove": {
      title: 'Remove Key-Value Pair',
      description: 'Compute the hash from the key to locate the bucket, search the bucket, and remove the matching key-value pair. Separate chaining requires handling linked-list node removal.',
      tips: 'Check whether the key exists before removing|Separate chaining needs a predecessor pointer to delete a node|Open addressing marks slots as "deleted" instead of truly removing them (to avoid breaking probe chains).',
      highlightTerms: 'splice|findIndex|remove',
      complexityTime: 'Average O(1), worst O(n)',
      complexitySpace: 'O(1)',
    },
  },
} as const
