/**
 * v20 M7 — learning config "heap" English locale（AI initial translation, subject to user review in M7-7）
 *
 * ⚠️ This file is generated by AI translation. Source: src/i18n/locales/zh/learning/heap.ts
 * User review pass: M7-7.
 *
 * Structure:
 *   title/description/complexityTime/complexitySpace: string
 *   tips/highlightTerms: string (separated by |, consumed as .split('|'))
 */
export const heapLearningSteps = {
  steps: {
    "init": {
      title: 'Build Heap',
      description: 'Starting from the last non-leaf node, perform heapify bottom-up to build a max-heap.',
      tips: 'Building the heap takes O(n), not O(n log n), because the bottom nodes do not need to sink.',
      highlightTerms: 'heapify|n / 2',
      complexityTime: 'O(n log n)',
      complexitySpace: 'O(1)',
    },
    "heapify": {
      title: 'Heapify Operation',
      description: 'Compare the parent with its left and right children, and bubble the largest up to the parent position.',
      tips: 'Heapify is a top-down recursive process; the worst case sinks all the way to a leaf, with depth log n.',
      highlightTerms: 'largest|arr[left]',
    },
    "extract": {
      title: 'Extract Top',
      description: 'Swap the top of the heap (the maximum) with the last element, then shrink the heap range.',
      tips: 'After each swap, the heap size decreases by 1 and the sorted region grows from the end backward.',
      highlightTerms: 'swap|0',
    },
    "sorted": {
      title: 'Sort Complete',
      description: 'Re-heapify after each extraction; repeat until the heap size is 1 and the array is fully sorted.',
      tips: 'Heap sort is the only sorting algorithm that is both O(n log n) in time and O(1) in space, but it is unstable.',
      highlightTerms: 'O(n log n)',
      complexityTime: 'O(n log n) stable',
      complexitySpace: 'O(1)',
    },
  },
} as const
