/**
 * v20 M7 — learning config "heapStructure" English locale（AI initial translation, subject to user review in M7-7）
 *
 * ⚠️ This file is generated by AI translation. Source: src/i18n/locales/zh/learning/heapStructure.ts
 * User review pass: M7-7.
 *
 * Structure:
 *   title/description/complexityTime/complexitySpace: string
 *   tips/highlightTerms: string (separated by |, consumed as .split('|'))
 */
export const heapStructureLearningSteps = {
  steps: {
    "structure": {
      title: 'Heap Structure',
      description: 'A heap is a complete binary tree stored in an array: the parent at index i has its left child at 2i+1 and its right child at 2i+2; in a max-heap the parent is greater than or equal to its children.',
      tips: 'A heap stores the complete binary tree in an array, avoiding pointers, with high space efficiency and cache friendliness.',
      highlightTerms: 'complete binary tree|≥',
      complexityTime: 'Insert/extract O(log n), peek O(1)',
      complexitySpace: 'O(n)',
    },
    "insert": {
      title: 'Insert (Sift Up)',
      description: 'A new element is placed at the end of the array, then compared with its parent; if it is greater than the parent, they are swapped and the element continues to sift up until the heap property is restored.',
      tips: 'Sift-up performs at most log n comparisons (the height of the tree), so insertion is O(log n).',
      highlightTerms: 'sift up|swap',
    },
    "extract": {
      title: 'Extract Top (Sift Down)',
      description: 'Swap the top of the heap with the last element, remove it, then sift down from the top by comparing with the larger child until the heap property is restored.',
      tips: 'Sift-down must always swap with the larger child, otherwise the heap property would be violated.',
      highlightTerms: 'sift down|largest',
    },
    "peek": {
      title: 'Peek Top',
      description: 'Return the first element of the array directly — the maximum value — in O(1) time.',
      tips: 'Typical heap applications: priority queues, heapsort, top-K problems, median maintenance, Dijkstra optimization.',
      highlightTerms: 'heap[0]|O(1)',
    },
  },
} as const
