/**
 * v20 M7 — learning config "insertion" English locale（AI initial translation, subject to user review in M7-7）
 *
 * ⚠️ This file is generated by AI translation. Source: src/i18n/locales/zh/learning/insertion.ts
 * User review pass: M7-7.
 *
 * Structure:
 *   title/description/complexityTime/complexitySpace: string
 *   tips/highlightTerms: string (separated by |, consumed as .split('|'))
 */
export const insertionLearningSteps = {
  steps: {
    "init": {
      title: 'Initialization',
      description: 'Starting from the second element (i=1), insert the current element into the correct position in the sorted region on the left.',
      tips: 'Insertion sort naturally divides the array into a "sorted" part and an "unsorted" part.',
      highlightTerms: 'i = 1|j',
      complexityTime: 'O(n²)',
      complexitySpace: 'O(1)',
    },
    "compare": {
      title: 'Compare Backward',
      description: 'Compare the current element with the adjacent element on the left; swap if the left element is larger.',
      tips: 'Stop as soon as you encounter an element that is not greater than the current one — this is the best-case optimization of insertion sort.',
      highlightTerms: 'arr[j - 1]|arr[j]',
    },
    "shift": {
      title: 'Shift Elements',
      description: 'Swap adjacent elements to move the current element leftward to its correct position.',
      tips: 'In practice, "shift" is often used instead of "swap" to reduce the number of assignments.',
      highlightTerms: 'temp|j--',
    },
    "sorted": {
      title: 'Sorted Region Grows',
      description: 'After each pass, arr[0..i] is sorted, and the algorithm continues with the next element.',
      tips: 'Insertion sort is extremely efficient on nearly sorted arrays, approaching O(n), and is often used as a subroutine in hybrid sort algorithms.',
      highlightTerms: 'sorted|O(n)',
      complexityTime: 'Best O(n), worst O(n²)',
      complexitySpace: 'O(1)',
    },
  },
} as const
