/**
 * v20 M7 — learning config "kruskal" English locale（AI initial translation, subject to user review in M7-7）
 *
 * ⚠️ This file is generated by AI translation. Source: src/i18n/locales/zh/learning/kruskal.ts
 * User review pass: M7-7.
 *
 * Structure:
 *   title/description/complexityTime/complexitySpace: string
 *   tips/highlightTerms: string (separated by |, consumed as .split('|'))
 */
export const kruskalLearningSteps = {
  steps: {
    "sort": {
      title: 'Sort Edges',
      description: 'Sort all edges in ascending order of weight; the greedy strategy starts by selecting the smallest edges.',
      tips: 'Sorting is the main time cost of Kruskal at O(E log E)|The greedy strategy guarantees the minimum total weight.',
      highlightTerms: 'sort|a.w - b.w',
      complexityTime: 'O(E log E)',
      complexitySpace: 'O(V)',
    },
    "union-find": {
      title: 'Union-Find Initialization',
      description: 'Use a Union-Find data structure to efficiently detect whether adding an edge forms a cycle.',
      tips: 'Path compression + union by rank make find/union nearly O(1)|Union-Find is the core data structure of Kruskal.',
      highlightTerms: 'UnionFind|find|union',
    },
    "select": {
      title: 'Greedy Selection',
      description: 'Iterate over the sorted edges; if an edge does not form a cycle, add it to the MST.',
      tips: 'If union returns false, u and v are already in the same set, so adding the edge would form a cycle|The MST has V-1 edges; stop once that count is reached.',
      highlightTerms: 'uf.union|mst.push',
    },
    "complete": {
      title: 'Algorithm Complete',
      description: 'The MST contains V-1 edges with the minimum total weight.',
      tips: 'Kruskal suits sparse graphs (few edges)|Unlike Prim, Kruskal sorts by edge rather than expanding by node.',
      highlightTerms: 'V - 1|totalWeight',
      complexityTime: 'O(E log E)',
      complexitySpace: 'O(V)',
    },
  },
} as const
