/**
 * v20 M7 — learning config "linkedlist" English locale（AI initial translation, subject to user review in M7-7）
 *
 * ⚠️ This file is generated by AI translation. Source: src/i18n/locales/zh/learning/linkedlist.ts
 * User review pass: M7-7.
 *
 * Structure:
 *   title/description/complexityTime/complexitySpace: string
 *   tips/highlightTerms: string (separated by |, consumed as .split('|'))
 */
export const linkedlistLearningSteps = {
  steps: {
    "init": {
      title: 'Linked List Structure',
      description: 'A linked list is composed of nodes; each node contains data and a pointer to the next node.',
      tips: 'Linked lists do not need contiguous memory; insertion/deletion only require pointer changes, but random access is O(n).',
      highlightTerms: 'value|next',
      complexityTime: 'Access O(n), insert/delete O(1)',
      complexitySpace: 'O(n)',
    },
    "insert-head": {
      title: 'Insert at Head',
      description: 'Insert a new node at the head of the list; the new node points to the original head.',
      tips: 'Head insertion is O(1) but reverses the order of elements.',
      highlightTerms: 'node.next|head',
    },
    "insert-tail": {
      title: 'Insert at Tail',
      description: 'Traverse to the end of the list and link the new node after the last node.',
      tips: 'Maintaining a tail pointer can optimize tail insertion to O(1), at the cost of extra maintenance.',
      highlightTerms: 'curr.next|while',
    },
    "insert-at": {
      title: 'Insert at Position',
      description: 'Traverse to the predecessor at the target position, then insert the new node between predecessor and successor.',
      tips: 'Handle the special case of index=0 (equivalent to head insert)|Time complexity is O(n) because you must traverse to the target position',
      highlightTerms: 'node.next|curr.next',
    },
    "delete": {
      title: 'Delete Node',
      description: 'Find the predecessor of the target index, then redirect the pointer to skip the target node.',
      tips: 'The key to deletion is finding the predecessor and "skipping" the target|Deleting the head node needs special handling because it has no predecessor',
      highlightTerms: 'curr.next.next',
    },
    "search": {
      title: 'Search',
      description: 'Traverse from the head, comparing each node value; return the matching index.',
      tips: 'Linked-list search can only traverse sequentially; random access (like arrays) is not possible|Time complexity is O(n) — this is the main drawback of linked lists over arrays',
      highlightTerms: 'curr.value === value|while',
    },
    "reverse": {
      title: 'Reverse',
      description: 'Use the three-pointer technique (prev/curr/next) to reverse each node\'s pointer one by one.',
      tips: 'The three-pointer technique is the standard way to reverse a linked list: O(n) time, O(1) space|Key: before modifying curr.next, save the next node first',
      highlightTerms: 'curr.next = prev|prev',
      complexityTime: 'O(n)',
      complexitySpace: 'O(1)',
    },
    "detect-cycle": {
      title: 'Cycle Detection',
      description: 'Floyd\'s tortoise-and-hare algorithm: the fast pointer advances two steps, the slow one step; if they meet, a cycle exists.',
      tips: 'Floyd\'s algorithm is O(n) time, O(1) space — optimal|If a cycle exists, slow and fast will meet inside the cycle; if not, fast reaches null first|After meeting, reset one pointer to head; both advance at the same speed and the second meeting point is the cycle entry',
      highlightTerms: 'slow === fast|fast.next.next',
      complexityTime: 'O(n)',
      complexitySpace: 'O(1)',
    },
  },
} as const
