/**
 * v20 M7 — learning config "merge" English locale（AI initial translation, subject to user review in M7-7）
 *
 * ⚠️ This file is generated by AI translation. Source: src/i18n/locales/zh/learning/merge.ts
 * User review pass: M7-7.
 *
 * Structure:
 *   title/description/complexityTime/complexitySpace: string
 *   tips/highlightTerms: string (separated by |, consumed as .split('|'))
 */
export const mergeLearningSteps = {
  steps: {
    "init": {
      title: 'Initialization',
      description: 'Repeatedly halve the array until each subarray has only one element.',
      tips: 'Merge sort uses a divide-and-conquer strategy; the splitting phase involves no comparisons or swaps.',
      highlightTerms: 'mid',
      complexityTime: 'O(n log n)',
      complexitySpace: 'O(n)',
    },
    "split": {
      title: 'Recursive Split',
      description: 'Recursively apply merge sort to the left and right halves.',
      tips: 'Recursion depth is log n; each level needs n operations in total, so the overall complexity is O(n log n).',
      highlightTerms: 'mergeSort',
    },
    "merge": {
      title: 'Merge Operation',
      description: 'Create a temporary array and use two pointers to merge two sorted subarrays into one sorted array.',
      tips: 'Using <= instead of < preserves the stability of merge sort.',
      highlightTerms: 'leftArr[i]|rightArr[j]',
    },
    "copy": {
      title: 'Copy Remainder',
      description: 'Copy any remaining elements from the two subarrays back into the original array.',
      tips: 'Merge sort requires O(n) extra space, which is a drawback, but it shines for linked-list and external sorting.',
      highlightTerms: 'leftArr[i]|arr[k]',
      complexityTime: 'O(n log n) stable',
      complexitySpace: 'O(n)',
    },
  },
} as const
