/**
 * v20 M7 — learning config "prim" English locale（AI initial translation, subject to user review in M7-7）
 *
 * ⚠️ This file is generated by AI translation. Source: src/i18n/locales/zh/learning/prim.ts
 * User review pass: M7-7.
 *
 * Structure:
 *   title/description/complexityTime/complexitySpace: string
 *   tips/highlightTerms: string (separated by |, consumed as .split('|'))
 */
export const primLearningSteps = {
  steps: {
    "init": {
      title: 'Initialization',
      description: 'Start from any node and add it to the minimum spanning tree (MST) set.',
      tips: 'Prim\'s algorithm expands the MST starting from one node|Best for dense graphs.',
      highlightTerms: 'inMST|start',
      complexityTime: 'O(V²)',
      complexitySpace: 'O(V)',
    },
    "select": {
      title: 'Select Minimum Edge',
      description: 'Among all edges with one endpoint in the MST and the other outside, pick the one with the smallest weight.',
      tips: 'The edge must have one endpoint inside the MST and one outside|Using a priority queue improves this to O(E log V).',
      highlightTerms: '!inMST.has(v)|w < minEdge.w',
    },
    "add": {
      title: 'Add to MST',
      description: 'Add the node corresponding to the minimum edge to the MST, and add the edge to the result set.',
      tips: 'If no minimum edge is found, the graph is disconnected and a full MST cannot be built.',
      highlightTerms: 'inMST.add|mst.push',
    },
    "complete": {
      title: 'Algorithm Complete',
      description: 'The MST contains V-1 edges, connecting all nodes with the smallest total weight.',
      tips: 'A minimum spanning tree always has V-1 edges|Prim suits dense graphs, while Kruskal suits sparse graphs.',
      highlightTerms: 'V-1|totalWeight',
      complexityTime: 'O(V²)',
      complexitySpace: 'O(V)',
    },
  },
} as const
