/**
 * v20 M7 — learning config "queue" English locale（AI initial translation, subject to user review in M7-7）
 *
 * ⚠️ This file is generated by AI translation. Source: src/i18n/locales/zh/learning/queue.ts
 * User review pass: M7-7.
 *
 * Structure:
 *   title/description/complexityTime/complexitySpace: string
 *   tips/highlightTerms: string (separated by |, consumed as .split('|'))
 */
export const queueLearningSteps = {
  steps: {
    "structure": {
      title: 'Queue Structure',
      description: 'A queue is a First-In-First-Out (FIFO) linear structure; elements are enqueued at the rear and dequeued at the front.',
      tips: 'Common applications: BFS traversal, task scheduling, message queues, print queues, buffers.',
      highlightTerms: 'FIFO|front|rear',
      complexityTime: 'All operations O(1)',
      complexitySpace: 'O(n)',
    },
    "enqueue": {
      title: 'Enqueue',
      description: 'Add a new element to the rear; the rear pointer advances. Time complexity is O(1).',
      tips: 'A circular queue can avoid the "false overflow" issue and make full use of the array space.',
      highlightTerms: 'push|O(1)',
    },
    "dequeue": {
      title: 'Dequeue',
      description: 'Remove and return the front element; the front pointer advances. Time complexity is O(1).',
      tips: 'JavaScript arrays shift() is O(n); use two pointers (front/rear) to avoid this overhead.',
      highlightTerms: 'queue.front++|empty',
    },
    "front": {
      title: 'Front',
      description: 'View the front element without removing it. The queue state is unchanged. Time complexity is O(1).',
      tips: 'A priority queue (heap) is a queue extension: dequeues return the highest-priority element.',
      highlightTerms: 'items[queue.front]|read-only',
    },
    "clear": {
      title: 'Clear',
      description: 'Remove all elements from the queue and reset the front and rear pointers. Time complexity is O(1) or O(n).',
      tips: 'After clearing the queue is empty|In a circular-queue implementation, reset front=0, rear=-1',
      highlightTerms: 'front|rear|clear',
      complexityTime: 'O(1) or O(n)',
      complexitySpace: 'O(1)',
    },
  },
} as const
