/**
 * v20 M7 — learning config "quick" English locale（AI initial translation, subject to user review in M7-7）
 *
 * ⚠️ This file is generated by AI translation. Source: src/i18n/locales/zh/learning/quick.ts
 * User review pass: M7-7.
 *
 * Structure:
 *   title/description/complexityTime/complexitySpace: string
 *   tips/highlightTerms: string (separated by |, consumed as .split('|'))
 */
export const quickLearningSteps = {
  steps: {
    "init": {
      title: 'Choose Pivot',
      description: 'Choose an element as the pivot, typically the last element.',
      tips: 'The choice of pivot directly affects performance; median-of-three helps avoid the worst case.',
      highlightTerms: 'pivot',
      complexityTime: 'Average O(n log n)',
      complexitySpace: 'O(log n)',
    },
    "partition": {
      title: 'Partition Operation',
      description: 'Iterate through the array, moving elements smaller than the pivot to the left and larger ones to the right.',
      tips: 'Partition is the core of quicksort — a single partition determines the final position of one element.',
      highlightTerms: 'arr[j]|pivot',
    },
    "place": {
      title: 'Place Pivot',
      description: 'Place the pivot in its correct position (i+1), with all elements on the left smaller and all on the right larger.',
      tips: 'After partitioning, the pivot is in its final position and needs no further movement.',
      highlightTerms: 'pi|i + 1',
    },
    "recurse": {
      title: 'Recursive Sort',
      description: 'Recursively apply quicksort to the subarrays on the left and right of the pivot.',
      tips: 'Quicksort has the best average performance, but the worst case O(n²) occurs on a sorted array when the pivot is the first or last element.',
      highlightTerms: 'quickSort',
      complexityTime: 'Worst O(n²)',
      complexitySpace: 'O(log n)',
    },
  },
} as const
