/**
 * v20 M7 — learning config "radix" English locale（AI initial translation, subject to user review in M7-7）
 *
 * ⚠️ This file is generated by AI translation. Source: src/i18n/locales/zh/learning/radix.ts
 * User review pass: M7-7.
 *
 * Structure:
 *   title/description/complexityTime/complexitySpace: string
 *   tips/highlightTerms: string (separated by |, consumed as .split('|'))
 */
export const radixLearningSteps = {
  steps: {
    "init": {
      title: 'Find Maximum',
      description: 'First find the maximum value in the array to determine the number of digits to process.',
      tips: 'Radix sort is a non-comparison sort; its time complexity can break through the O(n log n) lower bound.',
      highlightTerms: 'max|exp',
      complexityTime: 'O(d·n)',
      complexitySpace: 'O(n+k)',
    },
    "count": {
      title: 'Count Current Digit',
      description: 'For the current digit (ones/tens/...), count the frequency of each digit 0-9.',
      tips: 'This implementation uses LSD (Least Significant Digit) radix sort, processing from the ones digit upward.',
      highlightTerms: 'digit|count[digit]',
    },
    "place": {
      title: 'Place by Digit',
      description: 'Place each element into the correct position of the output array based on its current digit (reverse iteration preserves stability).',
      tips: 'Reverse iteration preserves stability — equal elements keep their original relative order.',
      highlightTerms: 'output|count[digit]',
    },
    "nextdigit": {
      title: 'Process Next Digit',
      description: 'Copy the output array back to the original array, multiply exp by 10 to move to the next digit, and repeat.',
      tips: 'Radix sort works well for sorting integers with a fixed number of digits and a limited range; d is the maximum number of digits.',
      highlightTerms: 'exp *= 10',
      complexityTime: 'O(d·n), d is the maximum number of digits',
      complexitySpace: 'O(n+k), k is the base',
    },
  },
} as const
