/**
 * v20 M7 — learning config "realWorldApplications" English locale（AI initial translation, subject to user review in M7-7）
 *
 * ⚠️ This file is generated by AI translation. Source: src/i18n/locales/zh/learning/realWorldApplications.ts
 * User review pass: M7-7.
 *
 * Structure:
 *   title/description/complexityTime/complexitySpace: string
 *   tips/highlightTerms: string (separated by |, consumed as .split('|'))
 */
export const realWorldApplicationsLearningSteps = {
  steps: {
    "browserHistory": {
      title: 'Browser History (Stack)',
      description: 'The browser\'s "back / forward" feature is implemented with two stacks: visiting a new page pushes the current page onto the back stack; going back pops from back and pushes onto forward; going forward does the reverse.',
      tips: 'Clearing the forward stack when visiting a new page is key: once you enter a new branch, the old forward history becomes invalid — a classic stack application.',
      highlightTerms: 'back stack|forward stack|LIFO',
      complexityTime: 'O(1) per operation',
      complexitySpace: 'O(n)',
    },
    "taskQueue": {
      title: 'Task Queue (Queue)',
      description: 'Message queues (RabbitMQ/Kafka), OS process scheduling, printer tasks, and the JavaScript event loop all rely on the FIFO property of queues to guarantee fair and ordered task processing.',
      tips: 'A queue is the embodiment of "fairness": first come, first served|Priority queues break fairness to schedule by priority (e.g., OS scheduling).',
      highlightTerms: 'FIFO|enqueue|dequeue|event loop',
      complexityTime: 'O(1) per operation',
      complexitySpace: 'O(n)',
    },
    "fileSystem": {
      title: 'File System (Tree)',
      description: 'A file system is a typical multi-way tree: directories are internal nodes, files are leaves. Path lookup, permission inheritance, and disk block allocation all depend on tree structures.',
      tips: 'Trees are the best expression of "hierarchical relationships": file systems, DOM, AST, database indexes, and org charts are all trees|Recursion is the natural tool for processing trees.',
      highlightTerms: 'multi-way tree|root|leaf|path lookup',
      complexityTime: 'O(h) for path lookup',
      complexitySpace: 'O(n)',
    },
    "socialNetwork": {
      title: 'Social Network (Graph)',
      description: 'A social network is modeled as a graph: users are nodes, follow / friend relationships are directed or undirected edges. Friend recommendation (mutual friends), shortest relationship chain (BFS), and community detection all depend on graph algorithms.',
      tips: '"Six degrees of separation" states that any two people are connected by at most 6 intermediaries — the social graph\'s BFS diameter is roughly 6.',
      highlightTerms: 'undirected graph|directed graph|mutual friends|six degrees',
      complexityTime: 'O(V+E) BFS',
      complexitySpace: 'O(V)',
    },
    "searchEngine": {
      title: 'Search Engine (Trie)',
      description: 'Search engine auto-complete, spell check, and keyword suggestion are built on Tries. Shared prefixes are stored compactly; prefix matching runs in O(word length), making it the core structure for string retrieval.',
      tips: 'The Radix Tree (compressed Trie) variant saves more space and is used by the Linux kernel routing table and HTTP/2 header compression.',
      highlightTerms: 'Trie|prefix match|auto-complete|frequency',
      complexityTime: 'O(m + k log k)',
      complexitySpace: 'O(total characters)',
    },
    "cache": {
      title: 'Cache (Hash Table)',
      description: 'An LRU cache uses a hash table plus a doubly linked list to achieve O(1) read/write. The hash table locates the key; the doubly linked list maintains access order. Redis, Memcached, browser cache, and CPU cache are all based on this idea.',
      tips: 'LRU (least recently used) is the most classic cache policy|There are also LFU (least frequently used), ARC, FIFO, etc.; Redis 4.0+ supports configurable LFU.',
      highlightTerms: 'hash table|doubly linked list|LRU|O(1)',
      complexityTime: 'O(1) get/put',
      complexitySpace: 'O(capacity)',
    },
  },
} as const
