/**
 * v20 M7 — learning config "redBlackTree" English locale（AI initial translation, subject to user review in M7-7）
 *
 * ⚠️ This file is generated by AI translation. Source: src/i18n/locales/zh/learning/redBlackTree.ts
 * User review pass: M7-7.
 *
 * Structure:
 *   title/description/complexityTime/complexitySpace: string
 *   tips/highlightTerms: string (separated by |, consumed as .split('|'))
 */
export const redBlackTreeLearningSteps = {
  steps: {
    "intro": {
      title: 'Red-Black Tree Introduction',
      description: 'A red-black tree is a self-balancing BST that uses node colors (red/black) and rotations to keep the tree approximately balanced, guaranteeing O(log n) operations.',
      tips: 'Red-black trees were invented by Rudolf Bayer in 1972, originally called "symmetric binary B-trees"|Linux CFS scheduler, Java TreeMap, C++ std::map all use red-black trees underneath|Compared to AVL trees, red-black trees perform fewer rotations and fit write-heavy workloads better',
      highlightTerms: 'color|red|parent',
      complexityTime: 'O(log n)',
      complexitySpace: 'O(n)',
    },
    "properties": {
      title: 'Five Red-Black Properties',
      description: 'A red-black tree maintains balance via five properties: black root, black leaves, no red-red parent-child, equal black-height on all paths.',
      tips: 'Property 4 forbids two consecutive red nodes|Property 5 guarantees the longest path is at most twice the shortest|NIL leaves refer to null nodes, which are implicitly black',
      highlightTerms: 'root|leaf|red node|black node',
    },
    "insert": {
      title: 'Insert Node',
      description: 'The new node defaults to red (to avoid breaking property 5); after BST insertion, run fixInsert to repair red-black properties.',
      tips: 'A red new node may violate property 4 (parent and child both red)|If the parent is black, no fix is needed|If the parent is red, enter fixInsert to repair',
      highlightTerms: 'newNode|parent|fixInsert',
      complexityTime: 'O(log n)',
      complexitySpace: 'O(1)',
    },
    "fixup": {
      title: 'Insert Fixup (Recolor + Rotate)',
      description: 'When the parent is red, fix in three cases based on the uncle color: recolor when uncle is red, rotate when uncle is black.',
      tips: 'Case 1 (red uncle): recolor, then move z up two levels; may need to continue|Case 2 (black uncle, z is inner): rotate the parent, transform into Case 3|Case 3 (black uncle, z is outer): recolor + rotate grandparent, done',
      highlightTerms: 'uncle|color|black|red',
      complexityTime: 'O(log n)',
      complexitySpace: 'O(1)',
    },
    "rotation": {
      title: 'Rotation Operations',
      description: 'Left and right rotations preserve the BST property and are the core of red-black tree rebalancing.',
      tips: 'A rotation is a local operation that only changes the pointer relationships of 3 nodes|Left and right rotations are inverse operations|BST inorder traversal is unchanged after a rotation',
      highlightTerms: 'rotateLeft|y|parent',
    },
    "complexity": {
      title: 'Complexity Analysis',
      description: 'Red-black tree height is at most 2·log(n+1); all operations are O(log n); rotations are fewer than AVL.',
      tips: 'Red-black tree insertion needs at most 2 rotations; AVL may need more|Red-black lookups are slightly slower than AVL (taller tree) but insert/delete are faster|Red-black trees are more widely used in practice (e.g., STL map/set)',
      highlightTerms: 'O(log n)|2 * log2|rotation',
    },
  },
} as const
