/**
 * v20 M7 — learning config "segmentTree" English locale（AI initial translation, subject to user review in M7-7）
 *
 * ⚠️ This file is generated by AI translation. Source: src/i18n/locales/zh/learning/segmentTree.ts
 * User review pass: M7-7.
 *
 * Structure:
 *   title/description/complexityTime/complexitySpace: string
 *   tips/highlightTerms: string (separated by |, consumed as .split('|'))
 */
export const segmentTreeLearningSteps = {
  steps: {
    "concept": {
      title: 'Segment Tree Concept',
      description: 'A binary tree structure where each node represents an interval, supporting efficient range queries and point updates.',
      tips: 'Segment trees were proposed by Jon Bentley in 1977|Each node represents an interval [start, end]|The root node represents the whole array [0, n-1]',
      highlightTerms: 'start|end|sum|left|right',
      complexityTime: 'O(log n)',
      complexitySpace: 'O(n)',
    },
    "node-structure": {
      title: 'Node Structure',
      description: 'Leaf nodes represent single elements; an internal node\'s interval is the concatenation of its left and right children.',
      tips: 'Leaf intervals have length 1|An internal node\'s sum = left.sum + right.sum|Tree height is O(log n)',
      highlightTerms: 'leaf node|internal node',
    },
    "build": {
      title: 'Build Operation',
      description: 'Build bottom-up recursively: leaf nodes store array elements, internal nodes store the sum of their children.',
      tips: 'Build time is O(n)|Recurse to leaves, then aggregate bottom-up|mid = (start + end) / 2, left child interval [start, mid], right child interval [mid+1, end]',
      highlightTerms: 'build|mid|left.sum + right.sum',
      complexityTime: 'O(n)',
      complexitySpace: 'O(n)',
    },
    "query": {
      title: 'Range Query',
      description: 'Recursive query: return 0 if no overlap, return sum if fully covered, recurse into both children if partially overlapping.',
      tips: 'Query time complexity is O(log n)|Three cases: no overlap, full overlap, partial overlap|For partial overlap, recurse into both children',
      highlightTerms: 'no overlap|full overlap|partial overlap',
      complexityTime: 'O(log n)',
      complexitySpace: 'O(log n)',
    },
    "update": {
      title: 'Point Update',
      description: 'Recurse from the root to the target leaf, update the value, then recompute sums bottom-up.',
      tips: 'Update time complexity is O(log n)|Only one root-to-leaf path needs to be updated|After updating, recompute the sums bottom-up',
      highlightTerms: 'index <= mid|node.left.sum + node.right.sum',
      complexityTime: 'O(log n)',
      complexitySpace: 'O(log n)',
    },
    "complexity": {
      title: 'Complexity Analysis',
      description: 'Build is O(n), query and update are both O(log n), space is O(n).',
      tips: 'Segment trees balance query and update speed|A prefix-sum is fast on queries but slow on updates; segment tree is fast on both|Maximum node count is 4n (because the last level may be partially filled)',
      highlightTerms: 'O(log n)|O(n)',
    },
    "applications": {
      title: 'Applications',
      description: 'Suited to scenarios with frequent range queries and point updates, such as range sum, range min/max, and counting.',
      tips: 'Lazy propagation supports range updates (e.g., range add, range assign)|Persistent segment tree (chairman tree) supports historical version queries|Segment tree is a frequent topic in competitions and interviews',
      highlightTerms: 'range sum|lazy propagation|persistent',
      complexityTime: 'O(log n)',
      complexitySpace: 'O(n)',
    },
  },
} as const
