/**
 * v20 M7 — learning config "selection" English locale（AI initial translation, subject to user review in M7-7）
 *
 * ⚠️ This file is generated by AI translation. Source: src/i18n/locales/zh/learning/selection.ts
 * User review pass: M7-7.
 *
 * Structure:
 *   title/description/complexityTime/complexitySpace: string
 *   tips/highlightTerms: string (separated by |, consumed as .split('|'))
 */
export const selectionLearningSteps = {
  steps: {
    "init": {
      title: 'Initialization',
      description: 'The outer loop starts from the beginning of the array; each pass selects the minimum element from the unsorted portion.',
      tips: 'Selection sort performs only one swap per pass — this is the key difference from bubble sort.',
      highlightTerms: 'minIdx|i',
      complexityTime: 'O(n²)',
      complexitySpace: 'O(1)',
    },
    "scan": {
      title: 'Scan Unsorted Region',
      description: 'Iterate from i+1 to n-1, finding the index of the minimum value.',
      tips: 'The inner loop only compares, never swaps, so the number of moves is O(n).',
      highlightTerms: 'arr[j]|arr[minIdx]|minIdx',
      complexityTime: 'O(n²)',
      complexitySpace: 'O(1)',
    },
    "swap": {
      title: 'Swap Minimum',
      description: 'Swap the found minimum with the current position i, placing it in its correct position.',
      tips: 'Selection sort is unstable: the relative order of equal elements may change.',
      highlightTerms: 'arr[i]|arr[minIdx]|temp',
    },
    "progress": {
      title: 'Shrink Range Progressively',
      description: 'After each pass, the sorted region expands by one, and the next pass continues selecting from the unsorted region.',
      tips: 'No matter the input data, selection sort is always O(n²) — there is no best-case optimization.',
      highlightTerms: 'sorted|unsorted',
    },
  },
} as const
