/**
 * v20 M7 — learning config "shell" English locale（AI initial translation, subject to user review in M7-7）
 *
 * ⚠️ This file is generated by AI translation. Source: src/i18n/locales/zh/learning/shell.ts
 * User review pass: M7-7.
 *
 * Structure:
 *   title/description/complexityTime/complexitySpace: string
 *   tips/highlightTerms: string (separated by |, consumed as .split('|'))
 */
export const shellLearningSteps = {
  steps: {
    "gap": {
      title: 'Choose Gap Sequence',
      description: 'Shell sort uses progressively shrinking gaps to sort subsequences. A common choice is the Knuth sequence: 1, 4, 13, 40, ...',
      tips: 'The choice of gap sequence directly affects time complexity|The Knuth sequence works well in practice and is simple to implement.',
      highlightTerms: 'gap * 3 + 1|Knuth',
      complexityTime: 'O(n log²n)',
      complexitySpace: 'O(1)',
    },
    "gap-sort": {
      title: 'Gapped Insertion Sort',
      description: 'For each gap, perform insertion sort on the subsequence formed by elements spaced gap apart.',
      tips: 'Large gaps let elements move across long distances, reducing comparisons|The final pass with gap=1 is a regular insertion sort, but the array is already nearly sorted by then.',
      highlightTerms: 'arr[j - gap] > arr[j]|j -= gap',
    },
    "complete": {
      title: 'Algorithm Complete',
      description: 'When the gap shrinks to 1, the final insertion sort completes and the array is sorted.',
      tips: 'Shell sort is an improvement on insertion sort that uses large gaps to quickly eliminate inversions|Unstable sort.',
      highlightTerms: 'gap=1|nearly sorted',
      complexityTime: 'O(n log²n)',
      complexitySpace: 'O(1)',
    },
  },
} as const
