/**
 * v20 M7 — learning config "skipList" English locale（AI initial translation, subject to user review in M7-7）
 *
 * ⚠️ This file is generated by AI translation. Source: src/i18n/locales/zh/learning/skipList.ts
 * User review pass: M7-7.
 *
 * Structure:
 *   title/description/complexityTime/complexitySpace: string
 *   tips/highlightTerms: string (separated by |, consumed as .split('|'))
 */
export const skipListLearningSteps = {
  steps: {
    "intro": {
      title: 'Skip List Introduction',
      description: 'A skip list is a probabilistic balanced data structure that uses multi-level linked lists to achieve O(log n) search — a simpler alternative to balanced trees.',
      tips: 'Skip lists were invented by William Pugh in 1989|Redis sorted sets (ZSET) use skip lists as the underlying structure|Compared with red-black trees, skip lists are simpler to implement and support range queries.',
      highlightTerms: 'head|level|MAX_LEVEL',
      complexityTime: 'O(log n)',
      complexitySpace: 'O(n)',
    },
    "structure": {
      title: 'Multi-Level Linked List',
      description: 'A skip list consists of multiple levels of linked lists. Level 0 contains every node, higher levels act as "express lanes" of the level below, and which levels a node appears in is decided randomly.',
      tips: 'Each node appears in level 0 and is promoted to higher levels with probability P|Higher levels are sparse and act as indexes|The expected number of levels is O(log n), which guarantees search efficiency.',
      highlightTerms: 'level 0|level 1|level 2',
    },
    "randomLevel": {
      title: 'Random Level Generation',
      description: 'When inserting a new node, a coin flip (probability P=0.5) determines the node\'s level, avoiding the complexity of manual balancing.',
      tips: 'P is usually 0.5, meaning a 50% chance to promote at each level|MAX_LEVEL caps the maximum level, typically 16 or 32|Randomness guarantees overall balance with no rotations required.',
      highlightTerms: 'randomLevel|Math.random|P',
      complexityTime: 'O(log n)',
      complexitySpace: 'O(1)',
    },
    "search": {
      title: 'Search Path',
      description: 'Start from the top level, move right until the next node value is greater than the target, then drop one level, and continue until level 0.',
      tips: 'Starting from the top level lets you quickly skip many nodes|When you reach level 0, the target is found or confirmed missing|The expected search path length is O(log n).',
      highlightTerms: 'forward[i]|level - 1|current',
      complexityTime: 'O(log n)',
      complexitySpace: 'O(1)',
    },
    "insert": {
      title: 'Insert and Link',
      description: 'Record the predecessor at each level while searching for the insertion position, then use randomLevel to decide the new node\'s level and link it into each level.',
      tips: 'The update array stores the predecessor at each level|The new node may have a level higher than the current level, requiring the level to be updated|Insertion runs in expected O(log n).',
      highlightTerms: 'update|randomLevel|forward',
      complexityTime: 'O(log n)',
      complexitySpace: 'O(log n)',
    },
    "delete": {
      title: 'Delete Node',
      description: 'Similar to insertion: record the predecessor at each level, then unlink the node at every level it appears in, and finally update the level.',
      tips: 'Deletion must update every level containing the node|The level may need to be lowered after deletion|Deletion runs in expected O(log n).',
      highlightTerms: 'update|forward|target',
      complexityTime: 'O(log n)',
      complexitySpace: 'O(log n)',
    },
    "complexity": {
      title: 'Complexity Analysis',
      description: 'All skip list operations run in expected O(log n) time with worst case O(n) (extremely unlikely); space complexity is O(n).',
      tips: 'Skip lists match red-black trees in performance but are simpler to implement|Skip lists support efficient range queries; red-black trees require in-order traversal|In concurrent settings, lock-free skip lists are easier to implement.',
      highlightTerms: 'O(log n)|O(n)',
    },
  },
} as const
