/**
 * v20 M7 — learning config "sortCompare" English locale（AI initial translation, subject to user review in M7-7）
 *
 * ⚠️ This file is generated by AI translation. Source: src/i18n/locales/zh/learning/sortCompare.ts
 * User review pass: M7-7.
 *
 * Structure:
 *   title/description/complexityTime/complexitySpace: string
 *   tips/highlightTerms: string (separated by |, consumed as .split('|'))
 */
export const sortCompareLearningSteps = {
  steps: {
    "select": {
      title: 'Choose Algorithms',
      description: 'Select 2-3 sorting algorithms from the top list to compare. It is recommended to choose algorithms of different complexities (e.g., bubble O(n²), merge O(n log n), heap O(n log n)) to observe the performance differences.',
      tips: 'Stable sorts (bubble, insertion, merge) preserve the relative order of equal elements|Unstable sorts (selection, quicksort, heap) do not guarantee the relative order of equal elements.',
      highlightTerms: 'bubble|quick|merge|heap',
      complexityTime: 'O(n²) ~ O(n log n)',
      complexitySpace: 'O(1) ~ O(n)',
    },
    "init": {
      title: 'Initialize Array',
      description: 'Click the "Random Generate" button to create a new random array. All selected algorithms will sort the same data, ensuring a fair comparison. The array is fixed at 15 elements (values 5-99).',
      tips: 'Using the same data ensures a fair comparison and prevents data differences from skewing the conclusion.',
      highlightTerms: 'data|[...data]',
    },
    "firstRound": {
      title: 'First Round Comparison',
      description: 'After clicking "Run All", all algorithms execute in parallel. Observe the differences in the first round: bubble sort compares adjacent elements and swaps gradually; selection sort first scans the entire array for the minimum; insertion sort inserts elements one by one into the sorted region.',
      tips: 'Bubble sort swaps up to n-1 times per pass|Selection sort swaps at most once per pass|Insertion sort is most efficient on nearly sorted data.',
      highlightTerms: 'arr[j]|minIdx|key',
      complexityTime: 'O(n²)',
      complexitySpace: 'O(1)',
    },
    "keyDiff": {
      title: 'Key Differences',
      description: 'Observe the comparison count (C) and swap count (S) at the top of each algorithm panel. Bubble sort has the most swaps; selection sort has the fewest swaps but many comparisons; merge and quick sorts have significantly fewer comparisons than O(n²) algorithms.',
      tips: 'Comparison count (C) reflects the total number of comparisons|Swap count (S) reflects the total amount of data movement|Actual performance depends on the sum of both, plus cache friendliness.',
      highlightTerms: 'compare|swap|n²/2|nlogn',
      complexityTime: 'O(n²) vs O(n log n)',
      complexitySpace: 'O(1) vs O(n)',
    },
    "complete": {
      title: 'Comparison Complete',
      description: 'After all algorithms finish, a performance comparison chart is shown at the bottom. The bar chart visualizes the comparison and swap counts of each algorithm. CSV/JSON data can be exported for post-class analysis. Conclusion: O(n log n) algorithms show a clear advantage as data size grows.',
      tips: 'In production, TimSort (default in Python/Java) is often used, combining the strengths of merge and insertion sort|There is no single "best" sort — only the sort best suited to the scenario.',
      highlightTerms: 'n < 20|n > 50|O(n log n)',
      complexityTime: 'O(n log n) best',
      complexitySpace: 'O(1) ~ O(n)',
    },
  },
} as const
