/**
 * v20 M7 — learning config "stack" English locale（AI initial translation, subject to user review in M7-7）
 *
 * ⚠️ This file is generated by AI translation. Source: src/i18n/locales/zh/learning/stack.ts
 * User review pass: M7-7.
 *
 * Structure:
 *   title/description/complexityTime/complexitySpace: string
 *   tips/highlightTerms: string (separated by |, consumed as .split('|'))
 */
export const stackLearningSteps = {
  steps: {
    "structure": {
      title: 'Stack Structure',
      description: 'A stack is a Last-In-First-Out (LIFO) linear structure where insertions and deletions happen only at the top.',
      tips: 'Common applications: function call stack, parenthesis matching, expression evaluation, browser back/forward navigation.',
      highlightTerms: 'LIFO|top',
      complexityTime: 'All operations O(1)',
      complexitySpace: 'O(n)',
    },
    "push": {
      title: 'Push',
      description: 'Place a new element on top of the stack; the top pointer moves up. Time complexity is O(1).',
      tips: 'Before pushing, check whether the stack is full (when implemented with a fixed-size array).',
      highlightTerms: 'stack.top|O(1)',
    },
    "pop": {
      title: 'Pop',
      description: 'Remove and return the top element; the top pointer moves down. Time complexity is O(1).',
      tips: 'Always check for an empty stack before popping, otherwise an underflow error will occur.',
      highlightTerms: 'stack.top--|empty',
    },
    "peek": {
      title: 'Peek',
      description: 'View the top element without removing it. The stack state is unchanged. Time complexity is O(1).',
      tips: 'In JavaScript, an array can simulate a stack: push/pop correspond to enstack/destack.',
      highlightTerms: 'items[stack.top]|read-only',
    },
    "clear": {
      title: 'Clear',
      description: 'Remove all elements from the stack and reset the top pointer to -1. Time complexity is O(1) (reset pointer only) or O(n) (clear the underlying array).',
      tips: 'After clearing the stack is empty; pop/peek will throw an underflow error again|An array implementation only needs to reset the top pointer to reuse the space',
      highlightTerms: 'top|clear',
      complexityTime: 'O(1) or O(n)',
      complexitySpace: 'O(1)',
    },
  },
} as const
