/**
 * v20 M7 — learning config "tim" English locale（AI initial translation, subject to user review in M7-7）
 *
 * ⚠️ This file is generated by AI translation. Source: src/i18n/locales/zh/learning/tim.ts
 * User review pass: M7-7.
 *
 * Structure:
 *   title/description/complexityTime/complexitySpace: string
 *   tips/highlightTerms: string (separated by |, consumed as .split('|'))
 */
export const timLearningSteps = {
  steps: {
    "run": {
      title: 'Run-based Insertion Sort',
      description: 'Split the array into runs of size RUN (usually 32) and insertion-sort each run. Insertion sort is efficient on small data.',
      tips: 'Insertion sort on small data approaches O(n)|RUN=32 is the empirically optimal value.',
      highlightTerms: 'RUN = 32|insertionSort',
      complexityTime: 'O(n log n)',
      complexitySpace: 'O(n)',
    },
    "merge": {
      title: 'Merge Sorted Runs',
      description: 'Progressively merge the sorted runs, doubling the merge span each time (32→64→128...).',
      tips: 'Merging sorted runs runs in O(n)|Combines the strengths of insertion sort and merge sort.',
      highlightTerms: 'merge|size *= 2',
    },
    "complete": {
      title: 'Algorithm Complete',
      description: 'All runs have been merged, and the array is sorted.',
      tips: 'TimSort is the industrial-grade sorting algorithm|Especially efficient on partially sorted data|Stable sort.',
      highlightTerms: 'Python/Java|O(n)',
      complexityTime: 'O(n log n)',
      complexitySpace: 'O(n)',
    },
  },
} as const
