/**
 * v20 M7 — learning config "topoSort" English locale（AI initial translation, subject to user review in M7-7）
 *
 * ⚠️ This file is generated by AI translation. Source: src/i18n/locales/zh/learning/topoSort.ts
 * User review pass: M7-7.
 *
 * Structure:
 *   title/description/complexityTime/complexitySpace: string
 *   tips/highlightTerms: string (separated by |, consumed as .split('|'))
 */
export const topoSortLearningSteps = {
  steps: {
    "init": {
      title: 'Compute In-Degrees',
      description: 'Iterate over every edge in the graph and count the in-degree of each node (how many edges point to it).',
      tips: 'A node with in-degree 0 does not depend on any other node, so it can be processed first.',
      highlightTerms: 'inDegree[neighbor]++',
      complexityTime: 'O(V+E)',
      complexitySpace: 'O(V)',
    },
    "queue": {
      title: 'Enqueue In-Degree 0',
      description: 'Enqueue every node with in-degree 0; they are the starting points of the topological order.',
      tips: 'If multiple nodes have in-degree 0, the topological order is not unique.',
      highlightTerms: 'inDegree[node] === 0|queue',
    },
    "process": {
      title: 'Process Node',
      description: 'Dequeue a node, add it to the result, and decrement the in-degree of all its neighbors by 1.',
      tips: 'Dequeuing is equivalent to "removing" the node and all of its outgoing edges from the graph.',
      highlightTerms: 'inDegree[neighbor]--|result.push',
    },
    "requeue": {
      title: 'Newly Ready Node',
      description: 'When a node\'s in-degree drops to 0, all of its prerequisites have been processed and it can be enqueued.',
      tips: 'In-degree becoming 0 is the signal that "all dependencies are satisfied" — the core idea of topological sort.',
      highlightTerms: 'inDegree[neighbor] === 0|push',
    },
    "cycle": {
      title: 'Cycle Detection and Result',
      description: 'If the length of the result is not equal to the number of nodes, the graph contains a cycle and topological sort is impossible.',
      tips: 'Common topological sort use cases: task scheduling, course planning, build dependencies, spreadsheet formula evaluation.',
      highlightTerms: 'result.length|cycle',
      complexityTime: 'O(V+E)',
      complexitySpace: 'O(V)',
    },
  },
} as const
