/**
 * v20 M7 — learning config "tree" English locale（AI initial translation, subject to user review in M7-7）
 *
 * ⚠️ This file is generated by AI translation. Source: src/i18n/locales/zh/learning/tree.ts
 * User review pass: M7-7.
 *
 * Structure:
 *   title/description/complexityTime/complexitySpace: string
 *   tips/highlightTerms: string (separated by |, consumed as .split('|'))
 */
export const treeLearningSteps = {
  steps: {
    "init": {
      title: 'Binary Tree Structure',
      description: 'Each node has at most two children: a left child and a right child.',
      tips: 'Binary Search Tree (BST) property: every value in the left subtree < root < every value in the right subtree.',
      highlightTerms: 'left|right',
      complexityTime: 'Average O(log n), worst O(n)',
      complexitySpace: 'O(n)',
    },
    "insert": {
      title: 'Insert Node',
      description: 'Compare the value with the current node: go left if smaller, right if larger, and insert at the first empty position.',
      tips: 'Insertion efficiency depends on tree height: O(log n) for balanced trees, O(n) for a degenerated list.',
      highlightTerms: 'value < node.value|left',
    },
    "traversal": {
      title: 'Traversal Methods',
      description: 'Preorder (root-left-right), inorder (left-root-right), postorder (left-right-root).',
      tips: 'Inorder traversal of a BST yields a sorted sequence — an important property.',
      highlightTerms: 'visit|inorder',
    },
    "preorder": {
      title: 'Preorder Traversal',
      description: 'Visit order: root → left subtree → right subtree. Commonly used for copying and serializing tree structures.',
      tips: 'The first node visited in preorder is the root|Can be used for tree serialization and deserialization',
      highlightTerms: 'visit|preorder',
      complexityTime: 'O(n)',
      complexitySpace: 'O(h), h = tree height',
    },
    "inorder": {
      title: 'Inorder Traversal',
      description: 'Visit order: left subtree → root → right subtree. BST inorder traversal yields a sorted sequence.',
      tips: 'BST inorder traversal is strictly increasing|Inorder traversal can be used to verify the BST property',
      highlightTerms: 'inorder|visit',
      complexityTime: 'O(n)',
      complexitySpace: 'O(h)',
    },
    "postorder": {
      title: 'Postorder Traversal',
      description: 'Visit order: left subtree → right subtree → root. Commonly used for deleting a tree and computing directory sizes.',
      tips: 'The last node visited in postorder is the root|Suitable for scenarios where subtrees must be processed before the root (e.g., memory deallocation)',
      highlightTerms: 'postorder|visit',
      complexityTime: 'O(n)',
      complexitySpace: 'O(h)',
    },
    "levelorder": {
      title: 'Level-Order Traversal',
      description: 'Visit nodes level by level, left to right. Implemented with a queue (BFS).',
      tips: 'Level-order traversal is the same as breadth-first search (BFS)|Commonly used to find minimum tree height and print trees by level',
      highlightTerms: 'queue|shift|push',
      complexityTime: 'O(n)',
      complexitySpace: 'O(w), w = max width',
    },
    "search": {
      title: 'Search Node',
      description: 'Using the BST property, compare the target value with the current node and go left or right accordingly.',
      tips: 'AVL and red-black trees maintain balance via rotations, guaranteeing O(log n) search.',
      highlightTerms: 'value < node.value|search',
    },
    "delete": {
      title: 'Delete Node',
      description: 'Deletion must handle three cases: leaf (remove directly), single child (replace with child), two children (replace with inorder successor).',
      tips: 'The two-children case can also use the inorder predecessor|Deletion may break balance; AVL/red-black trees need rotations to recover',
      highlightTerms: 'findMin|deleteNode|inorder successor',
      complexityTime: 'Average O(log n), worst O(n)',
      complexitySpace: 'O(h)',
    },
  },
} as const
