/**
 * v20 M7 — learning config "trie" English locale（AI initial translation, subject to user review in M7-7）
 *
 * ⚠️ This file is generated by AI translation. Source: src/i18n/locales/zh/learning/trie.ts
 * User review pass: M7-7.
 *
 * Structure:
 *   title/description/complexityTime/complexitySpace: string
 *   tips/highlightTerms: string (separated by |, consumed as .split('|'))
 */
export const trieLearningSteps = {
  steps: {
    "structure": {
      title: 'Trie Structure',
      description: 'A trie is a multi-way tree where each edge represents a character, and the path from the root to a node forms a prefix.',
      tips: 'A trie trades space for time: it uses O(total characters) space in exchange for O(word length) lookup time.',
      highlightTerms: 'prefix|isEnd',
      complexityTime: 'O(m), m is the word length',
      complexitySpace: 'O(total characters)',
    },
    "insert": {
      title: 'Insert Word',
      description: 'Walk down the path character by character, creating a new node when one does not exist; the final character node is marked as the end of a word.',
      tips: 'Words with shared prefixes share path nodes — this is the key to how tries save space.',
      highlightTerms: 'isEnd|children[ch]',
    },
    "search": {
      title: 'Search Word',
      description: 'Walk down the path character by character. If the path is broken, the word does not exist; on reaching the end, check the isEnd flag.',
      tips: 'Distinguish between "search word" and "search prefix": the former needs the isEnd check, the latter does not.',
      highlightTerms: 'path broken|isEnd',
    },
    "prefix": {
      title: 'Prefix Match',
      description: 'Similar to search, but the isEnd flag is not required — as long as the path exists, the match succeeds. Useful for auto-completion.',
      tips: 'Typical trie applications: search engine auto-complete, spell check, IP routing tables, word frequency counting.',
      highlightTerms: 'prefix missing|auto-complete',
    },
    "remove": {
      title: 'Remove Word',
      description: 'Recursively find the word path and prune nodes from the leaves up. Only delete nodes that are not shared by other words; keep shared prefixes.',
      tips: 'Confirm the word exists before deleting|Shared prefix nodes must not be deleted (other words still use them)|Setting isEnd to false is enough for a "soft delete".',
      highlightTerms: 'isEnd|delete|remove',
      complexityTime: 'O(m), m is the word length',
      complexitySpace: 'O(m) recursion stack',
    },
  },
} as const
