/**
 * v20 M7 — learning config "unionFind" English locale（AI initial translation, subject to user review in M7-7）
 *
 * ⚠️ This file is generated by AI translation. Source: src/i18n/locales/zh/learning/unionFind.ts
 * User review pass: M7-7.
 *
 * Structure:
 *   title/description/complexityTime/complexitySpace: string
 *   tips/highlightTerms: string (separated by |, consumed as .split('|'))
 */
export const unionFindLearningSteps = {
  steps: {
    "intro": {
      title: 'Union-Find Introduction',
      description: 'Union-Find (Disjoint Set Union) is a data structure that efficiently handles merging and querying of disjoint sets, with amortized time complexity close to O(1).',
      tips: 'Union-Find was proposed by Bernard Galler and Michael Fischer in 1964|Widely used for connectivity problems, minimum spanning trees (Kruskal), and network connectivity|Path compression + union by rank drive the amortized complexity to O(α(n)) ≈ O(1).',
      highlightTerms: 'parent|rank|constructor',
      complexityTime: 'O(α(n))',
      complexitySpace: 'O(n)',
    },
    "makeSet": {
      title: 'Initialize Sets',
      description: 'Each element initially forms its own set, with parent pointing to itself and rank set to 0.',
      tips: 'At initialization, every node is the root of its own set|rank is an upper bound on tree height and starts at 0|parent[x] === x is how you identify a root.',
      highlightTerms: 'makeSet|parent|rank',
    },
    "find": {
      title: 'Find Root (Path Compression)',
      description: 'Find the root of the set a node belongs to, and point every node on the path directly to the root to accelerate subsequent queries.',
      tips: 'Path compression flattens the tree, making later queries faster|Recursive implementations are concise; iterative ones avoid stack overflow|Path compression does not change rank; rank is only an upper bound on height.',
      highlightTerms: 'find|parent[x]|path compression',
      complexityTime: 'O(α(n))',
      complexitySpace: 'O(α(n))',
    },
    "union": {
      title: 'Union Sets (By Rank)',
      description: 'Merge the sets containing two elements, using union by rank to keep trees shallow.',
      tips: 'Union by rank attaches the shorter tree under the taller one, avoiding linked-list degradation|When ranks are equal, pick either root and increment its rank|Path compression + union by rank = amortized O(α(n)).',
      highlightTerms: 'union|rank|parent',
      complexityTime: 'O(α(n))',
      complexitySpace: 'O(1)',
    },
    "connected": {
      title: 'Connectivity Query',
      description: 'Determine whether two elements belong to the same set by comparing their roots.',
      tips: 'Connectivity queries are the most central application of union-find|Connected components of an undirected graph can be solved efficiently with union-find|Judging whether two people are indirectly connected in a social network.',
      highlightTerms: 'connected|find',
      complexityTime: 'O(α(n))',
      complexitySpace: 'O(1)',
    },
    "components": {
      title: 'Count Connected Components',
      description: 'Count the number of connected components in a graph — that is, the number of distinct roots.',
      tips: 'The number of components equals the number of distinct roots|Kruskal\'s algorithm uses union-find to detect cycles|An efficient solution for dynamic connectivity problems.',
      highlightTerms: 'countComponents|Set|find',
      complexityTime: 'O(n·α(n))',
      complexitySpace: 'O(n)',
    },
    "complexity": {
      title: 'Complexity Analysis',
      description: 'Path compression + union by rank give union-find amortized O(α(n)) for every operation, where α is the inverse Ackermann function, which grows extremely slowly.',
      tips: 'α(n) is the inverse Ackermann function, which grows extremely slowly|In practice, α(n) can be treated as a constant (< 5)|Union-find is one of the optimal solutions to dynamic connectivity.',
      highlightTerms: 'O(α(n))|O(1)|O(n)',
    },
  },
} as const
